# Generated by Django 4.1.7 on 2023-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='slug',
            field=models.CharField(default='7c9de9bc2bd44c8d', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='39aa1f2885f84fbd', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='waiter_wallet',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
