# Generated by Django 4.1.7 on 2023-05-26 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_cafe_slug_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='slug',
            field=models.CharField(default='cc21ad3875824a14', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_wallet',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='5509397ec8f34ecf', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='waiter_wallet',
            field=models.CharField(blank=True, max_length=42, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
    ]
