# Generated by Django 4.1.7 on 2023-06-03 17:03

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_alter_cafe_slug_alter_customer_customer_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tips.models.cafe_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=tips.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='slug',
            field=models.CharField(default='5cfae2c84f214b47', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='f9abc7f787f448bf', max_length=20, unique=True),
        ),
    ]
